# Name: Amy Seo
# Email: amyseo@g.ucla.edu
# ID: 505328863

default: lab1.c
	gcc -g -Wall -Wextra -o lab1a lab1.c

dist: lab1.c README Makefile
	tar -cvzf lab1a-505328863.tar.gz README lab1.c Makefile

clean:
	rm -rf *.tar.gz lab1a