# NAME: Muthu Palaniappan, Amy Seo
# EMAIL: muthupal@g.ucla.edu, amyseo@ucla.edu
# ID: 005292734, 505328863

.SILENT: 

default:
	chmod +x makeDefault.sh
	./makeDefault.sh

dist: 
	tar -cvzf lab3b-505328863.tar.gz lab3b.py makeDefault.sh README Makefile

clean:
	rm -f *.tar.gz lab3b