# NAME: Muthu Palaniappan, Amy Seo
# EMAIL: muthupal@g.ucla.edu, amyseo@ucla.edu
# ID: 005292734, 505328863

.SILENT: 

default:
	gcc -Wall -Wextra -g -o lab3a lab3a.c 

dist: 
	tar -cvzf lab3a-505328863.tar.gz ext2_fs.h lab3a.c README Makefile

clean:
	rm -f *.tar.gz lab3a  *.o